name: CI Pipline
on:
  push:
    branches: [ main ]
concurrency:
  group: 'deployments'
  cancel-in-progress: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - run: echo "${{secrets.DOCKERHUB_USERNAME}}/Deploying to production environment."

  docker:
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    environment: production
    permissions:
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Set image tag
        run: echo "IMAGE_TAG=git-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cubicle-app:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cubicle-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Deploy to productionserver
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cubicle-app:${{ env.IMAGE_TAG }}
            sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cubicle-app:${{ env.IMAGE_TAG }} cubicle-app:latest
            sudo docker stop cubicle-app || true
            sudo docker rm cubicle-app || true
            sudo docker run -d --name cubicle-app -p 80:80 cubicle-app:${{ env.IMAGE_TAG }}