name: CI Pipline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo "Deploying to staging environment..."
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-stage
    permissions:
      contents: read
    steps:
      - run: echo "${{secrets.DOCKERHUB_USERNAME}}/Deploying to production environment..."